[package]
name = "rocket-study"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = { version = "9.3.0", features = ["use_pem"] }
rocket = { version = "0.5.1", features = ["json", "secrets", "serde_json"] }

[profile.dev]
opt-level = 3
